object Versions {
    const val kotlinV = "1.7.0"
    const val composeVersion = "1.1.0"
    const val coreKtx = "1.8.0"
    const val lifeCycleRunTimeKtx = "2.5.0"
    const val activityCompose = "1.5.0"
    const val appCompat = "1.4.2"
    const val materialDesign = "1.6.1"
    const val junitV = "4.13.2"
    const val androidXJunitV = "1.1.3"
    const val espressoVersion = "3.4.0"
    const val daggerHilt = "2.38.1"
    const val viewModelHilt = "1.0.0-alpha03"
    const val daggerCompiler = "2.37"
    const val hiltCompiler = "1.0.0"
    const val composeNavigationVersion = "2.5.0"
    const val accompanistVersion = "0.24.9-beta"
    const val retrofitVersion = "2.9.0"
    const val gsonConverterVersion = "2.9.0"
    const val okhttpVersion = "5.0.0-alpha.3"
    const val loggingInterceptorVersion = "5.0.0-alpha.3"
    const val hiltNavigation = "1.0.0-alpha03"
    const val composeConstraintLayout = "1.0.1"
    const val accompanistPermissions = "0.21.1-beta"
    const val gsonVersion = "2.8.2"
}