# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Upload Lint report - App Module
        uses: actions/upload-artifact@v2
        with:
          name: main_app_lint_report.html
          path: app/build/reports/lint-results-debug.html
      - name: Upload Lint report - Authentication Module
          uses: actions/upload-artifact@v2
          with:
            name: authentication_lint_report.html
            path: authentication/build/reports/lint-results-debug.html
